### ISSUE TITLE
Support Remote App (Application access) in RDP ?

### ISSUE THREAD

**Issue by HRNasr** [casbin/casvisor#22]

**Comment by hsluoyz** [comment]
@HRNasr do you want something like this: https://stackoverflow.com/questions/52254357/guacamole-rdp-remote-app-within-a-black-box ?

![image](https://github.com/casbin/casvisor/assets/3787410/f49e0071-42e1-4ae9-bfd7-b912dd49f3ae)

What's your scenario for specifying the application to be accessed in RDP? Like sharing a calculator via a shared link to others (in https://github.com/casbin/casvisor/issues/21) ?

**Comment by HRNasr** [comment]
Yes. Exactly using Microsoft's RDS feature
